export const vaishnavBhojan = [
  "LORD KRISHNA IS PLEASED WHEN VAISHNAVA ARE SERVED ",

  " ANNA DAAN IS MAHA DAAN ",

  "FEED THE VAISHNAVA OF ISKCON VRINDAVAN AND GET BLESSINGS OF LORD KRISHNA FOR YOUR FAMILY ",
];
