export const founder = [
  "Srila A.C. Bhaktivedanta Swami Prabhupada was a spiritual master, a founder-acharya of the International Society for Krishna Consciousness (ISKCON), and a profound scholar of the Vedic scriptures. Born Abhay Charan De in Calcutta, India, in 1896, and spent his early life studying the Vedic scriptures and practicing devotional service to Lord Krishna.",
  "In 1965, at the age of 69, Srila Prabhupada boarded a cargo ship bound for New York City with only a few belongings and a burning desire to spread the teachings of Lord Krishna to the Western world, as per the instructions of his spiritual master Srila Bhaktisiddhanta Saraswati Goswami Maharaj Prabhupada. Despite numerous obstacles and setbacks, he persevered, living in poverty and facing countless challenges as he worked tirelessly to establish the first ISKCON temple in New York City.",
  "Over the next 11 years, Srila Prabhupada traveled extensively, establishing temples, ashrams, and centers around the world and inspiring countless individuals to embrace the path of bhakti-yoga. His teachings on love, compassion, and devotion to God continue to resonate with people of all backgrounds, and his legacy has touched the lives of millions.",
  "Srila Prabhupada's contributions to the world of spirituality and religion are immeasurable. Through his translations and commentaries on the Bhagavad-gita and Srimad Bhagavatam, he has provided a profound understanding of the ancient wisdom of the Vedic scriptures. His emphasis on the importance of devotional service and compassion for all living beings has inspired countless individuals to embrace a life of spiritual practice and service to others.",
  "Srila Prabhupada's contributions to the world of spirituality and religion are immeasurable. Through his translations and commentaries on the Bhagavad-gita and Srimad Bhagavatam, he has provided a profound understanding of the ancient wisdom of the Vedic scriptures. His emphasis on the importance of devotional service and compassion for all living beings has inspired countless individuals to embrace a life of spiritual practice and service to others.",
  "Srila Prabhupada's teachings and example continue to inspire new generations of seekers and spiritual aspirants, and his legacy lives on through the vibrant and growing ISKCON movement that he founded. His dedication, wisdom, and unwavering commitment to the path of Krishna consciousness remain an inspiration to all who seek the truth and meaning of life.",
  "Srila Prabhupada Chronology",
  "1954 Left family, vanaprastha",
  "1956 Vrindavan residence, Vamsi Gopal temple",
  "1959 Begins translating Srimad Bhagavatam in Delhi",
  "July Moves upstairs Radha-Damodara temple",
  "Sept. 17, Takes sannyasa, renounced order of life",
  "1960 Fall Publishes first book, paperback Easy Journey to Other Planets",
  "1962 July Moves into downstairs rooms at Radha-Damodara",
  "Sept. Publishes Volume one, Srimad Bhagavatam in Delhi",
  "1963 December Publishes volume two Srimad Bhagavatam",
  "1964 December Publishes volume three Srimad Bhagavatam",
  "1965 August 13, Leaves Calcutta on Jaladuta bound for America",
  "1967 Returns to Radha-Damodara",
  "1971 Visits Radha-Damodara and Vrindavan with forty disciples",
  "1972 Kartik at Radha-Damodara, delivers famous Nectar of Devotion Lectures",
  "1977 Enters the eternal lila of Radha and Krishna in Goloka Vrindavan.",
];
