export const routes = {
  home: "/",
  festival: "/festival",
  contact: "/contact",
  donation: "/donation",
  visitUs: "/visit-us",
  media: "/media",
  bookDistribution: "/services/book-distribtion",
  deityWorship: "/services/deity-worship",
  devoteeKitchen: "/services/devotee-kitchen",
  gaushala: "/services/gaushala",
  guestHouse: "/services/guest-house",
  iskconYouthForum: "/srevices/iskcon-youth-forum",
  kirtanAtIskcon: "/services/kirtan-at-iskcon",
  lifeTimeMembership: "/services/life-time-membership",
  cancellationPolicy: "/footer/cancellation-policy",
  privacyPolicy: "/footer/privacy-policy",
  termsAndCondition: "/footer/terms-and-condition,",
  annaDaan: "/donation-pages/anna-daan",
  ekadasi: "/donation-pages/ekadasi",
  gauraPurnima: "/donation-pages/gaura-purnima",
  gauSeva: "/donation-pages/gau-seva",
  hariNaamKirtanSeva: "/donation-pages/harinaam-kirtan-seva",
  vaishnavBhojan: "/donation-pages/vaishnav-bhojan",
  naivaidyamSeva: "/donation-pages/naivaidyam-seva",
  vigarhSeva: "/donation-pages/vigrah-seva",
};
